// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518053839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Models.WorkspaceAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_workspace_actions_updated_at_utc");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workspace_actions_workspace_id");

                    b.ToTable("workspace_actions", (string)null);
                });

            modelBuilder.Entity("Models.WorkspaceActionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_name_snapshot");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("OutputPreview")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("output_preview");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TargetSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_snapshot");

                    b.Property<int>("WorkspaceActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_action_id");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_action_runs_started_at_utc");

                    b.HasIndex("WorkspaceActionId")
                        .HasDatabaseName("ix_action_runs_workspace_action_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_action_runs_workspace_id");

                    b.ToTable("action_runs", (string)null);
                });

            modelBuilder.Entity("Models.WorkspaceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("LastOpenedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_opened_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resume_text");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("root_path");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LastOpenedAtUtc")
                        .HasDatabaseName("ix_workspaces_last_opened_at_utc");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_workspaces_updated_at_utc");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Models.WorkspaceNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_workspace_notes_updated_at_utc");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_workspace_notes_workspace_id");

                    b.ToTable("workspace_notes", (string)null);
                });

            modelBuilder.Entity("Models.WorkspaceAction", b =>
                {
                    b.HasOne("Models.WorkspaceItem", null)
                        .WithMany("Actions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.WorkspaceActionRun", b =>
                {
                    b.HasOne("Models.WorkspaceAction", null)
                        .WithMany("ActionRuns")
                        .HasForeignKey("WorkspaceActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.WorkspaceNote", b =>
                {
                    b.HasOne("Models.WorkspaceItem", null)
                        .WithMany("Notes")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.WorkspaceAction", b =>
                {
                    b.Navigation("ActionRuns");
                });

            modelBuilder.Entity("Models.WorkspaceItem", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
